name: deploy-client

on:
    push:
        branches:
            - main
        paths:
            - 'Client/**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd Client && docker build -t adi2911/next-client .
            - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              env:
                DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
                DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
            - run: docker push adi2911/next-client
            - uses: digitalocean/action-doctl@v2
              with:
                token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
            - run: doctl kubernetes cluster kubeconfig save bookmyevent
            - run: kubectl rollout restart deployment client-deploy