name: deploy-ticket

on:
    push:
        branches:
            - main
        paths:
            - 'Ticket/**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd Ticket && docker build -t adi2911/ticket-service .
            - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              env:
                DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
                DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
            - run: docker push adi2911/ticket-service
            - uses: digitalocean/action-doctl@v2
              with:
                token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
            - run: doctl kubernetes cluster kubeconfig save bookmyevent
            - run: kubectl rollout restart deployment ticket-deploy